"""add_secret_findings

Revision ID: 1106351c8ef3
Revises: 9df9e66bc376
Create Date: 2026-05-09 15:04:45.063753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1106351c8ef3'
down_revision: Union[str, Sequence[str], None] = '9df9e66bc376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('detector_name', sa.String(length=100), nullable=False),
    sa.Column('raw_secret', sa.Text(), nullable=True),
    sa.Column('redacted', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['scope_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_secret_detector', 'secret_findings', ['detector_name'], unique=False)
    op.create_index('ix_secret_status', 'secret_findings', ['status'], unique=False)
    op.create_index('ix_secret_target', 'secret_findings', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_secret_target', table_name='secret_findings')
    op.drop_index('ix_secret_status', table_name='secret_findings')
    op.drop_index('ix_secret_detector', table_name='secret_findings')
    op.drop_table('secret_findings')
    # ### end Alembic commands ###
