"""add_takeover_findings

Revision ID: 21c8ad6c009f
Revises: 1106351c8ef3
Create Date: 2026-05-09 15:08:06.296323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c8ad6c009f'
down_revision: Union[str, Sequence[str], None] = '1106351c8ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('takeover_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subdomain_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('cname_value', sa.String(length=500), nullable=False),
    sa.Column('fingerprint_matched', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subdomain_id'], ['subdomains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_takeover_service', 'takeover_findings', ['service'], unique=False)
    op.create_index('ix_takeover_subdomain', 'takeover_findings', ['subdomain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_takeover_subdomain', table_name='takeover_findings')
    op.drop_index('ix_takeover_service', table_name='takeover_findings')
    op.drop_table('takeover_findings')
    # ### end Alembic commands ###
