"""add_program_scope_and_normalize_host

Revision ID: 9df9e66bc376
Revises: fa937d8c48b2
Create Date: 2026-05-09 14:48:40.604546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df9e66bc376'
down_revision: Union[str, Sequence[str], None] = 'fa937d8c48b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_scopes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('program_handle', sa.String(length=255), nullable=False),
    sa.Column('in_scope', sa.JSON(), nullable=False),
    sa.Column('out_of_scope', sa.JSON(), nullable=False),
    sa.Column('bounty_min', sa.Integer(), nullable=True),
    sa.Column('bounty_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['scope_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('live_hosts', sa.Column('raw_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_hosts', 'raw_url')
    op.drop_table('program_scopes')
    # ### end Alembic commands ###
