"""initial schema

Revision ID: fa937d8c48b2
Revises: 
Create Date: 2026-05-08 20:36:50.347471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa937d8c48b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scope_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('program', sa.String(length=255), nullable=True),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target')
    )
    op.create_table('dns_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('record_type', sa.String(length=10), nullable=False),
    sa.Column('record_value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['scope_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dns_domain', 'dns_records', ['domain'], unique=False)
    op.create_index('ix_dns_target', 'dns_records', ['target_id'], unique=False)
    op.create_table('scan_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('workflow', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_phase', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['scope_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_status', 'scan_sessions', ['status'], unique=False)
    op.create_index('ix_session_target', 'scan_sessions', ['target_id'], unique=False)
    op.create_table('subdomains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('subdomain', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['scope_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'subdomain', name='uq_subdomain_per_target')
    )
    op.create_index('ix_subdomain_resolved', 'subdomains', ['resolved'], unique=False)
    op.create_index('ix_subdomain_target', 'subdomains', ['target_id'], unique=False)
    op.create_table('live_hosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subdomain_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('web_server', sa.String(length=100), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('ssl_info', sa.JSON(), nullable=True),
    sa.Column('roi_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subdomain_id'], ['subdomains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_live_host_url')
    )
    op.create_index('ix_live_host_roi', 'live_hosts', ['roi_score'], unique=False)
    op.create_index('ix_live_host_subdomain', 'live_hosts', ['subdomain_id'], unique=False)
    op.create_table('scan_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=100), nullable=False),
    sa.Column('tool', sa.String(length=100), nullable=False),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('return_code', sa.Integer(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['scan_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifact_session', 'scan_artifacts', ['session_id'], unique=False)
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('live_host_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['live_host_id'], ['live_hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_endpoint_live_host', 'endpoints', ['live_host_id'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('live_host_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('matched_at', sa.String(length=1024), nullable=True),
    sa.Column('curl_command', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['live_host_id'], ['live_hosts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vuln_live_host', 'vulnerabilities', ['live_host_id'], unique=False)
    op.create_index('ix_vuln_severity', 'vulnerabilities', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vuln_severity', table_name='vulnerabilities')
    op.drop_index('ix_vuln_live_host', table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index('ix_endpoint_live_host', table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index('ix_artifact_session', table_name='scan_artifacts')
    op.drop_table('scan_artifacts')
    op.drop_index('ix_live_host_subdomain', table_name='live_hosts')
    op.drop_index('ix_live_host_roi', table_name='live_hosts')
    op.drop_table('live_hosts')
    op.drop_index('ix_subdomain_target', table_name='subdomains')
    op.drop_index('ix_subdomain_resolved', table_name='subdomains')
    op.drop_table('subdomains')
    op.drop_index('ix_session_target', table_name='scan_sessions')
    op.drop_index('ix_session_status', table_name='scan_sessions')
    op.drop_table('scan_sessions')
    op.drop_index('ix_dns_target', table_name='dns_records')
    op.drop_index('ix_dns_domain', table_name='dns_records')
    op.drop_table('dns_records')
    op.drop_table('scope_targets')
    # ### end Alembic commands ###
